export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const FETCH_USER_START = 'FETCH_USER_START';

export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

